"""Pydantic models for API and LangGraph state definitions."""

from typing import TypedDict, List, Optional, Annotated
from pydantic import BaseModel, Field


# LangGraph State
class GraphState(TypedDict):
    """State managed by the LangGraph workflow."""
    messages: Annotated[List[dict], "Chat history messages"]
    generated_query: Optional[List[str]]  # The SQL query generated by the LLM
    query_results: Optional[str]  # Results from executing the query
    error_message: Optional[List[str]]
    summary_context: Optional[str]  # Summary from previous session (for reset feature)
    retry_count: int  # Track number of retries to limit loops
    validation_result: Optional[str]  # Result from query validation
    retrieved_schema: Optional[str] 
    schema_to_check: int


# FastAPI Request/Response Models
class ChatRequest(BaseModel):
    """Request model for the /chat endpoint."""
    session_id: str = Field(..., description="Unique session identifier")
    user_input: str = Field(..., description="User's natural language query")


class ChatResponse(BaseModel):
    """Response model for the /chat endpoint."""
    session_id: str = Field(..., description="Session identifier")
    response: str = Field(..., description="LLM's response to the user")
    sql_query: Optional[str] = Field(None, description="Generated SQL query")
    query_results: Optional[List[dict]] = Field(None, description="Query execution results")
    error_message: Optional[str] = Field(None, description="Error message if any")


class HistoryResponse(BaseModel):
    """Response model for the /history endpoint."""
    session_id: str = Field(..., description="Session identifier")
    messages: List[dict] = Field(..., description="Chat history for the session")
    generated_query: Optional[str] = Field(None, description="The SQL query generated by the LLM")
    query_results: Optional[List[dict]] = Field(None, description="Results from executing the query")
    error_message: Optional[str] = Field(None, description="Error message if query execution fails")
    summary_context: Optional[str] = Field(None, description="Summary from previous session")
    retry_count: int = Field(0, description="Number of retries attempted")
    validation_result: Optional[str] = Field(None, description="Result from query validation")


class ResetRequest(BaseModel):
    """Request model for the /session/reset endpoint."""
    session_id: str = Field(..., description="Session identifier to reset")


class ResetResponse(BaseModel):
    """Response model for the /session/reset endpoint."""
    session_id: str = Field(..., description="Session identifier")
    summary: str = Field(..., description="Summary of the previous conversation")
    message: str = Field(..., description="Status message")

