from graph.schema import GraphState
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from utils import get_llm, create_column_names_for_schemas, extract_json_from_text, ommiting_think_block
from typing import Literal
from langchain_core.runnables import RunnableConfig

import json
import os


def explain_query_error(state: GraphState, config: RunnableConfig) -> GraphState:
    """
    Use LLM to explain the reason for a query execution error.
    
    Args:
        user_prompt: The user's original question/prompt
        generated_query: The SQL query that was generated
        error: The error message from run_query()
        
    Returns:
        A detailed explanation of why the query failed, generated by the LLM
    """
    model_name = config.get("configurable", {}).get("model_name", "gpt")
    llm = get_llm(model_id=model_name)

    # Get needed columns
    validation_result = state.get("validation_result", {})
    if isinstance(validation_result, str):
        try:
            validation_result = extract_json_from_text(validation_result)
        except (json.JSONDecodeError, ValueError):
            validation_result = {}

    all_schemas_metadata = create_column_names_for_schemas(validation_result['Needed table and categories'])

    user_messages = [msg for msg in state.get("messages", []) if msg["role"] == "user"]
    user_prompt = user_messages[-1]["content"] if user_messages else ""

    with open(os.path.join('..', 'prompt_template', 'error_handling_system_prompt.txt')) as f:
        system_prompt = f.read()

    with open(os.path.join('..', 'prompt_template', 'error_handling_user_prompt_part_1.txt')) as f:
        user_prompt_text = f.read().format(all_schemas_metadata, user_prompt)

    queries = [q for q in state.get("generated_query", [])]
    error_messages = [err for err in state.get("error_message", [])]

    for i, (q, err) in enumerate(zip(queries, error_messages)):
        with open(os.path.join('..', 'prompt_template', 'error_handling_user_prompt_part_2.txt')) as f:
            p = f.read().format(i, q, err)
        user_prompt_text += p

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_prompt_text)
    ]

    response = llm.invoke(messages)
    response = ommiting_think_block(response.content)
    response = extract_json_from_text(response.strip())

    state["error_explanation"] = response["error_explanation"]
    state["generated_query"].append(response["corrected_query"])
    
    return response


def should_retry(state: GraphState, config: RunnableConfig) -> Literal["retry", "end"]:
    """Conditional edge: Decide whether to retry or end."""
    error = state.get("error_message")
    retry_count = state.get("retry_count", 0)
    
    if error and retry_count < 3:
        return "retry"
    
    return "end"


def error_handler(state: GraphState, config: RunnableConfig) -> GraphState:
    """Node 3: Handle errors and prepare for retry or final response."""
    # Increment retry count if there's an error
    error = state.get("error_message")
    if error:
        retry_count = state.get("retry_count", 0)
        state["retry_count"] = retry_count + 1
    return state