"""Pydantic models for API and LangGraph state definitions."""

from typing import TypedDict, List, Optional, Annotated
from pydantic import BaseModel, Field


class GraphState(TypedDict):
    """State managed by the LangGraph workflow."""
    messages: Annotated[List[dict], "Chat history messages"]
    generated_query: Optional[List[str]]  # The SQL query generated by the LLM
    query_results: Optional[str]  # Results from executing the query
    error_message: Optional[List[str]]
    summary_context: Optional[str]  # Summary from previous session (for reset feature)
    retry_count: int  # Track number of retries to limit loops
    validation_result: Optional[str]  # Result from query validation
    retrieved_schema: Optional[str]
    query_explanation: int
    retrieved_columns: Optional[str] # Added field to store schema metadata
    keywords: str


# class GraphState_(TypedDict):
#     """
#     Represents the state of our graph.

#     Attributes:
#         question: The user's question.
#         keywords: Keywords extracted from the user's question.
#         retrieved_schema: The relevant schema parts retrieved from ChromaDB.
#         sql_query: The generated SQL query.
#         query_result: The result of the executed SQL query.
#         error: Any error messages encountered.
#         retries: The number of retries for SQL execution.
# """
#     question: str
#     keywords: str
#     retrieved_schema: str
#     sql_query: str
#     query_result: str
#     error: str
#     retries: int
