"""Pydantic models for API and LangGraph state definitions."""

from typing import TypedDict, List, Optional, Annotated
from pydantic import BaseModel, Field


class GraphState(TypedDict):
    """State managed by the LangGraph workflow."""
    messages: Annotated[List[dict], "Chat history messages"]
    generated_query: Optional[List[str]]  # The SQL query generated by the LLM
    query_results: Optional[str]  # Results from executing the query
    error_message: Optional[List[str]]
    summary_context: Optional[str]  # Summary from previous session (for reset feature)
    retry_count: int  # Track number of retries to limit loops
    validation_result: Optional[str]  # Result from query validation
    retrieved_schema: Optional[str]
    query_explanation: int
    retrieved_columns: Optional[str] # Added field to store schema metadata
    keywords: str
    query_generation_user_prompt: str